#!/bin/bash

read -p "Do you want to start the vpn? = " input

case "$input" in
	"y")
		echo "Starting your vpn...."
		hotspotshield connect
		;;
	"n")
		echo "Disconnecting your vpn..."
		hotspotshield disconnect
		;;
	*)
		echo "Provide values y/n only..."
		exit 1
		;;
esac
